version: '3'
services:
  test-db:
    container_name: test-db
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - '5432:5432'
    env_file:
      - ./env/.env.db
    volumes:
      - ./db_data:/var/lib/postgresql/data