version: '3'
services:
  test-db:
    container_name: test-db
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - '5432:5432'
    networks:
      - test-net
    env_file:
      - ./env/.env.db
    volumes:
      - ./db_data:/var/lib/postgresql/data

  test-redis:
    container_name: test-redis
    image: redis
    restart: on-failure
    volumes:
      - ./redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - test-net

networks:
  test-net:
    external: true
    driver: bridge
